# Generated by Django 4.0.1 on 2022-01-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ived_id', models.CharField(blank=True, max_length=6, unique=True)),
            ],
        ),
    ]
